name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  detekt:
    name: Detekt Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      
      - name: Run Detekt
        run: ./gradlew detekt --no-daemon
      
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
        continue-on-error: true
      
      - name: Upload Detekt report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: build/reports/detekt/
          retention-days: 30

  ktlint:
    name: Ktlint Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      
      - name: Run Ktlint
        run: ./gradlew ktlintCheck --no-daemon
      
      - name: Upload Ktlint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-report
          path: |
            **/build/reports/ktlint/
          retention-days: 30

  dependency-check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      
      - name: Check dependencies
        run: ./gradlew dependencyUpdates --no-daemon
        continue-on-error: true
      
      - name: Upload dependency report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: build/dependencyUpdates/
          retention-days: 30

  build-validation:
    name: Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      
      - name: Check build configuration
        run: ./gradlew projects --no-daemon
      
      - name: Compile all modules
        run: ./gradlew assemble -x generateReleaseBaselineProfile --no-daemon
      
      - name: Check for unused dependencies
        run: ./gradlew buildHealth --no-daemon
        continue-on-error: true
